[package]
name = "reloadables_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["rlib", "dylib"]


[dependencies]
bevy = { version = "0.12", default_features = false }
dexterous_developer = { path = "../../../dexterous_developer" }
serde = { version = "1", features = ["derive"] }

[workspace]
