[package]
name = "dexterous_developer_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lib_dexterous_developer_example"
path = "src/lib.rs"
crate-type = ["rlib"]

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy" }
dexterous_developer = { path = "../dexterous_developer" }
serde = "*"

[features]
orange = []

[workspace]
