[workspace]
resolver = "2"
members = [
    "dexterous_developer_macros",
    "dexterous_developer",
    "dexterous_developer_cli",
    "dexterous_developer_internal",
    "dexterous_developer_dynamic",
]

exclude = [
    "testing",
    "dexterous_developer_example",
    "no_cli_launcher",
    "tools/ci",
]

[workspace.package]
version = "0.1.0"
authors = ["Lee-Orr"]
description = "An experimental hot reload system for the bevy game engine. "
license = "MIT OR Apache-2.0"
categories = ["games", "game-development"]
keywords = ["bevy"]
homepage = "https://lee-orr.github.io/dexterous_developer/"
repository = "https://github.com/lee-orr/dexterous_developer"
documentation = "https://lee-orr.github.io/dexterous_developer/"


# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
