[workspace]
resolver = "2"
members = [
    "dexterous_developer_macros",
    "dexterous_developer",
    "dexterous_developer_cli",
    "dexterous_developer_internal",
    "dexterous_developer_dynamic",
    "bevy_dexterous_developer",
    "dexterous_developer_example",
    "testing/dexterous_developer_tests",
    "testing/templates/*",
    "testing/tmp/*"
]

exclude = [
    "tools/ci",
    "testing/templates/remote_client",
    "testing/tmp/tmp_can_run_remote_client",
    "testing/tmp/tmp_can_update_assets_client",
]

[workspace.package]
version = "0.1.0"
authors = ["Lee-Orr"]
description = "A modular hot reload system for rust"
license = "MIT OR Apache-2.0"
categories = ["games", "game-development", "hot-reload", "ui", "servers", "gui"]
keywords = ["bevy"]
homepage = "https://lee-orr.github.io/dexterous_developer/"
repository = "https://github.com/lee-orr/dexterous_developer"
documentation = "https://lee-orr.github.io/dexterous_developer/"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
