[package]
name = "dexterous_developer_cli"
version = "0.0.10"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "../README.md"
categories = ["games", "game-development"]
keywords = ["bevy"]
exclude = ["assets/**/*", "tools/**/*", ".github/**/*"]
authors = ["Lee-Orr"]
homepage = "https://lee-orr.github.io/dexterous_developer/"
repository = "https://github.com/lee-orr/dexterous_developer"
documentation = "https://lee-orr.github.io/dexterous_developer/"
description = "A CLI for hot reloadable apps in bevy, using the dexterous_developer crate"

[dependencies]
dexterous_developer_internal = { path = "../dexterous_developer_internal", version = "0.0.10", default-features = false, features = [
    "hot",
    "cli",
] }
clap = { version = "4", features = ["derive"] }
axum = { version = "0.6", features = ["ws"] }
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.20"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4.0", features = ["fs", "trace"] }
anyhow = "1"
url = { version = "2", features = ["serde"] }
futures-util = { version = "0.3", default-features = false, features = [
    "sink",
    "std",
] }
crossbeam = "0.8"
blake3 = "1"
walkdir = "2"
notify = { version = "6", default-features = false, features = [
    "macos_kqueue",
] }
dunce = "1"
directories = "5"
semver = "1"
which = "4"
toml = "0.8"
cargo_metadata = { version = "0.18" }
