[package]
name = "dexterous_developer"
version = "0.0.10"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "../README.md"
categories = ["games", "game-development"]
keywords = ["bevy"]
exclude = ["assets/**/*", "tools/**/*", ".github/**/*"]
authors = ["Lee-Orr"]
homepage = "https://lee-orr.github.io/dexterous_developer/"
repository = "https://github.com/lee-orr/dexterous_developer"
documentation = "https://lee-orr.github.io/dexterous_developer/"
description = "a hot-reload library for bevy"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["bevy"]
hot = ["dexterous_developer_internal/hot"]
hot_internal = [
    "dexterous_developer_internal/hot_internal",
    "dexterous_developer_dynamic",
]
bevy = ["dexterous_developer_internal/bevy"]
cli = ["dexterous_developer_internal/cli"]


[dependencies]
dexterous_developer_internal = { version = "0.0.10", path = "../dexterous_developer_internal", default-features = false }
dexterous_developer_dynamic = { version = "0.0.10", path = "../dexterous_developer_dynamic", optional = true }
