[package]
name = "xilem_dexterous_developer_library"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
exclude = ["assets/**/*", "tools/**/*", ".github/**/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
hot = [
    "dexterous_developer_internal/hot"
]
hot_internal = [
    "dexterous_developer_internal/hot_internal",
    "dep:libloading",
    "dep:uuid",
    "dep:chrono",
]


[dependencies]
anyhow = { version = "1" }
dexterous_developer_types = { version = "0.3.0-pre.1", path = "../../../../dexterous_developer_types" }
dexterous_developer_internal = { version = "0.3.0-pre.1", path = "../../../../dexterous_developer_internal" }
xilem = { git = "https://github.com/linebender/xilem" }
masonry = { git = "https://github.com/linebender/xilem" }
serde = { version = "1", features = ["derive"] }
rmp-serde = { version = "1" }
chrono = { version = "0.4", optional = true }
libloading = { version = "0.8", optional = true }
uuid = { version = "1", features = ["v4"], optional = true }
tracing = { version = "0.1" }
tracing-subscriber = {  version = "0.3", features = ["env-filter", "fmt"]}
paste = { version = "1" }
once_cell = "1"
typetag = "0.2"
safer-ffi = { version = "0.1", features = ["dyn-traits", "alloc"] }
abi_stable = "0.11"